global:
  storageClass: "longhorn"

ingress:
  enabled: true
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix

postgresql-ha:
  enabled: true
  diagnosticMode:
    enabled: false
  postgresql:
    image:
      tag: 16.4.0-debian-12-r34

postgresql:
  enabled: false

# TODO: Fix Redis properly
redis-cluster:
  enabled: true

gitea:
  config:
    server:
      LFS_START_SERVER: true
