apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
data:
  # Kubernetes base64 encodes the data
  # By default, this is:
  default-email: cGdhZG1pbkBleGFtcGxlLmNvbQ== # pgadmin@example.com
  default-password: ZGF0YWJhc2U= # database