apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume-claim
  labels:
    app: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi