apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/mysql