apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.11

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres