apiVersion: v1
kind: Service
metadata:
  namespace: matrix-dendrite-personal
  name: dendrite
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.21
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: dendrite
    app.kubernetes.io/name: dendrite
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: http
