env:
  DB_HOSTNAME: "postgres-postgresql"

immich:
  persistence:
    library:
      existingClaim: immich-pvc

machine-learning:
  persistence:
    cache:
      size: 25Gi
      type: pvc
      storageClass: nfs-client

redis:
  enabled: true

postgresql:
  enabled: false

server:
  ingress:
    main:
      enabled: true

image:
  tag: v1.123.0
