apiVersion: v1
kind: Service
metadata:
  name: pgadmin

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: pgadmin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  rules:
  - host: "pgadmin.hofers.cloud"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              name: web