apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/pgadmin