apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-kube
spec:
  hostname: ts-kube
  subnetRouter:
    advertiseRoutes:
      - "10.0.0.0/24"
      - "192.168.0.0/24"
      - "192.168.1.0/24"
      - "192.168.2.0/24"
  exitNode: true
