apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-volume-claim
  namespace: kube-system
  labels:
    app: traefik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
