apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-volume-claim
  labels:
    app: traefik
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
