apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certs-volume
  labels:
    type: local
    app: traefik
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /ssl-certs/