#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
        - country-mirror
        - arches: &id001
            - amd64
            - i386
          uri: http://archive.ubuntu.com/ubuntu/
        - arches: &id002
            - s390x
            - arm64
            - armhf
            - powerpc
            - ppc64el
            - riscv64
          uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
      - arches: *id001
        uri: http://security.ubuntu.com/ubuntu/
      - arches: *id002
        uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: false
  drivers:
    install: false
  kernel:
    package: linux-generic
  keyboard:
    layout: us
    toggle: null
    variant: ""
  locale: en_US.UTF-8
  oem:
    install: auto
  source:
    id: ubuntu-server-minimal
    search_drivers: false
  identity:
    realname: Cluster Administrator
  ssh:
    allow-pw: false
    install-server: true
  storage:
    layout:
      name: lvm
      match:
          path: /dev/vda
  updates: security
  version: 1
