image:
  repository: tensorchord/pgvecto-rs
  tag: pg14-v0.2.0
global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      username: immich
      database: immich
      password: immich
primary:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  persistence:
    enabled: true
    existingClaim: data-immich-postgresql-0
  resources:
    limits:
      memory: 1024Mi
  initdb:
    scripts:
      create-extensions.sql: |
        CREATE EXTENSION cube;
        CREATE EXTENSION earthdistance;
        CREATE EXTENSION vectors;
