apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-immich-postgresql-0
  namespace: immich
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
